using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Logging;
using VibeFunctionsIsolated.Models.Cosmos;
using VibeFunctionsIsolated.Models.Square;
using VibeFunctionsIsolated.Utility.UtilityInterfaces;

namespace VibeFunctionsIsolated.Functions.CalendarEvents;

public class UpsertCalendarEvent(
        ILogger<UpsertCalendarEvent> logger,
        IApplicationUtility applicationUtility,
        ICalendarEventUtility cosmosCalendarEventUtility,
        ISquareUtility squareUtility) 
{
    private readonly ILogger<UpsertCalendarEvent> logger = logger;
    private readonly IApplicationUtility applicationUtility = applicationUtility;
    private readonly ICalendarEventUtility cosmosCalendarEventUtility = cosmosCalendarEventUtility;
    private readonly ISquareUtility squareUtility = squareUtility;

    [Function("UpsertCalendarEvent")]
    public async Task<IActionResult> Run([HttpTrigger(AuthorizationLevel.Function, "post")] HttpRequest req)
    {
        CalendarEvent? calendarEvent = await applicationUtility.DeserializeStream<CalendarEvent>(req.Body);

        if (calendarEvent == null)
        {
            string upsertEventClass = nameof(UpsertCalendarEvent);
            logger.LogError("{upsertEventClass}: Invalid request body", upsertEventClass);

            return new BadRequestObjectResult("Invalid request body");
        }

        CatalogItemIds? squareUpsertIds = await squareUtility.UpsertCalendarEvent(calendarEvent);

        if (squareUpsertIds != null)
        {
            // If a new calendar event is created, assign the id generated by square
            // to the calendar event before upserting to cosmos
            if (calendarEvent.SquareEventId != squareUpsertIds.ItemId && squareUpsertIds.VariationIds.Any())
            {
                calendarEvent.SquareEventId = squareUpsertIds.ItemId;
                calendarEvent.SquareVariationId = squareUpsertIds.VariationIds.First(); // The First variation contains extra data not in the item itself
                calendarEvent.SquareEventVersion = squareUpsertIds.DatabaseVersion;
            }

            bool didCosomosUpsert = await cosmosCalendarEventUtility.UpsertCalendarEvent(calendarEvent);

            if (didCosomosUpsert)
                return new OkResult();
        }

        return new BadRequestResult();
    }
}
